apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: wheel/logger:0.1.0
        command: ["wheel-logger"]
        envFrom:
        - configMapRef:
            name: logger-config
