apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: wheel/client:0.1.0
        command: ["cargo", "run"]
        envFrom:
        - configMapRef:
            name: client-config
